// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BadMintonData.Models;

public partial class BookingDetail
{
    public Guid BookingDetailId { get; set; }

    public Guid BookingId { get; set; }

    public string CustomerId { get; set; }

    public Guid SlotId { get; set; }

    public string CourtId { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual CourtSlot Slot { get; set; }
}