// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BadMintonData.Models;

public partial class Booking
{
    public Guid BookingId { get; set; }

    public Guid CustomerId { get; set; }

    public Guid CourtId { get; set; }

    public Guid SlotId { get; set; }

    public string PaymentType { get; set; }

    public DateTime BookingDate { get; set; }

    public bool PaymentStatus { get; set; }

    public double TotalPrice { get; set; }

    public string Address { get; set; }

    public string Code { get; set; }

    public string Description { get; set; }

    public string Phone { get; set; }

    public string Status { get; set; }

    public virtual ICollection<BookingDetail> BookingDetails { get; set; } = new List<BookingDetail>();

    public virtual Court Court { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual CourtSlot Slot { get; set; }
}