// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BadMintonData.Models;

public partial class Court
{
    public Guid CourtId { get; set; }

    public string CourtName { get; set; }

    public string Location { get; set; }

    public bool IsActive { get; set; }

    public string Area { get; set; }

    public string BadmintonNet { get; set; }

    public string Descrip { get; set; }

    public string OwnerName { get; set; }

    public string Seats { get; set; }

    public string Status { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual ICollection<CourtSlot> CourtSlots { get; set; } = new List<CourtSlot>();
}