// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BadMintonData.Models;

public partial class CourtSlot
{
    public Guid SlotId { get; set; }

    public Guid CourtId { get; set; }

    public string SlotStartTime { get; set; }

    public string SlotEndTime { get; set; }

    public bool Status { get; set; }

    public string SlotPrice { get; set; }

    public virtual ICollection<BookingDetail> BookingDetails { get; set; } = new List<BookingDetail>();

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual Court Court { get; set; }
}