// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BadMintonData.Models;

public partial class Customer
{
    public Guid CustomerId { get; set; }

    public bool Gender { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string Address1 { get; set; }

    public string Address2 { get; set; }

    public bool IsActive { get; set; }

    public string Cccd { get; set; }

    public DateTime Dob { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();
}